version: '3'
services:
  vault0:
    image: vault:1.12.2
    command: server
    environment:
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_LOCAL_CONFIG={"storage":{"raft":{}},"listener":{"tcp":{"address":"0.0.0.0:8200","tls_disable":true}}}
      - VAULT_RAFT_PATH=/vault/file
      - VAULT_RAFT_NODE_ID=node0
      - VAULT_CLUSTER_ADDR=http://vault0:8201
      - VAULT_UI=true
    cap_add:
    - IPC_LOCK
    ports:
      - 8200:8200

  vault1:
    image: vault:1.12.2
    command: server
    environment:
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_LOCAL_CONFIG={"storage":{"raft":{}},"listener":{"tcp":{"address":"0.0.0.0:8200","tls_disable":true}}}
      - VAULT_RAFT_PATH=/vault/file
      - VAULT_RAFT_NODE_ID=node1
      - VAULT_CLUSTER_ADDR=http://vault1:8201
      - VAULT_UI=true
    cap_add:
    - IPC_LOCK
    ports:
      - 8300:8200

  vault2:
    image: vault:1.12.2
    command: server
    environment:
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_LOCAL_CONFIG={"storage":{"raft":{}},"listener":{"tcp":{"address":"0.0.0.0:8200","tls_disable":true}}}
      - VAULT_RAFT_PATH=/vault/file
      - VAULT_RAFT_NODE_ID=node2
      - VAULT_CLUSTER_ADDR=http://vault2:8201
      - VAULT_UI=true
    cap_add:
    - IPC_LOCK
    ports:
      - 8400:8200

  mongo0.example.com:
    image: mongo:6.0
    command: --replSet=s0 --wiredTigerCacheSizeGB=0.25 --tlsCertificateKeyFile=/data/mongo.pem --tlsMode=requireTLS
    secrets:
    - source: mongo0.pem
      target: /data/mongo.pem
    volumes:
    - mongo0:/data/db

  mongo1.example.com:
    image: mongo:6.0
    command: --replSet=s0 --wiredTigerCacheSizeGB=0.25 --tlsCertificateKeyFile=/data/mongo.pem --tlsMode=requireTLS
    secrets:
    - source: mongo1.pem
      target: /data/mongo.pem 
    volumes:
    - mongo1:/data/db

  mongo2.example.com:
    image: mongo:6.0
    command: --replSet=s0 --wiredTigerCacheSizeGB=0.25 --tlsCertificateKeyFile=/data/mongo.pem --tlsMode=requireTLS
    secrets:
    - source: mongo2.pem
      target: /data/mongo.pem
    volumes:
    - mongo2:/data/db

volumes:
  mongo0:
  mongo1:
  mongo2:

secrets:
  mongo0.pem:
    file: ./certs/mongo0.example.com.pem
  mongo1.pem:
    file: ./certs/mongo1.example.com.pem
  mongo2.pem:
    file: ./certs/mongo2.example.com.pem

